import sys
import json
import datetime


TEMPLATE = """
/**
 * Please don't update this file manually
 * Auto generated by src/poseidon/generate_constants.py
 *
 * Last Modified: {last_modified}
 * Params: {params}
*/
pub const ROUNDSF: u8 = 8;
pub const ROUNDSP: u8 = 60;

pub const WIDTH: usize = 5;

pub const ROUND_CONSTANTS_HEX: [&str; 340] = {round_constants};

pub const MDS_MATRIX_HEX: [[&str; WIDTH]; WIDTH] = {mds_constants};
"""

CONSTANTS_FILE_PATH = "./constants.rs"

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Please provide the path to the files containing the ark and mds matrix constants")
        exit(1)

    ark_constants_path = sys.argv[1]
    mds_constants_path = sys.argv[2]

    ark_constants = []
    with open(ark_constants_path, "r") as fh:
        c = fh.read().strip().replace("'", "\"").replace("0x", "")
        ark_constants = json.loads(c)
        fh.close()

    mds_constants = []
    with open(mds_constants_path, "r") as fh:
        c = fh.read().strip().replace("'", "\"").replace("0x", "")
        mds_constants = json.loads(c)
        fh.close()

    ark = json.dumps(ark_constants, indent=4)
    mds = json.dumps(mds_constants, indent=4)
    res = TEMPLATE.replace("{round_constants}", ark) \
        .replace("{mds_constants}", mds) \
        .replace("{last_modified}", str(datetime.datetime.now())) \
        .replace("{params}", ", ".join(sys.argv[1:]))

    with open(CONSTANTS_FILE_PATH, "w") as fw:
        fw.write(res)
