/*!
 * Please don't update this file manually
 * Auto generated by contrib/seeds/generate_seeds.py
 *
 * Last Modified: 2022-05-20 21:01:32.592805
*/

use super::PeerAddress;
#[allow(unused_imports)]
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};

pub fn seed_bootstrap_nodes() -> Vec<PeerAddress> {
    vec![
        // --- BEGIN BOOTSTRAP NODES ---
        // --- END BOOTSTRAP NODES ---
    ]
}
